# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContents = QtWidgets.QWidget()
        self.scrollAreaContents.setGeometry(QtCore.QRect(0, 0, 501, 549))
        self.scrollAreaContents.setObjectName("scrollAreaContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollAreaArea = QtWidgets.QVBoxLayout()
        self.scrollAreaArea.setObjectName("scrollAreaArea")
        self.verticalLayout.addLayout(self.scrollAreaArea)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.downButtons = QtWidgets.QHBoxLayout()
        self.downButtons.setObjectName("downButtons")
        self.addNew = QtWidgets.QPushButton(self.centralwidget)
        self.addNew.setObjectName("addNew")
        self.downButtons.addWidget(self.addNew)
        self.verticalLayout_4.addLayout(self.downButtons)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addNew.setText(_translate("MainWindow", "Add New"))
